version: "3"

services:
  # backend
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - TOKEN= # Your Discord BOT Token
      - PREFIX= # Your Personal Prefix, you can set it later using command "prefix"
      - INGAT_CHANNEL= # Where your pengingat will be send
      - USER_ID= # Someone that will be tagged when pengigat is send